/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRouteImport } from './routes/track'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as ShippingDeliveryRouteImport } from './routes/shipping-delivery'
import { Route as ReturnsCancellationsRouteImport } from './routes/returns-cancellations'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PhilosophyRouteImport } from './routes/philosophy'
import { Route as OurStoreRouteImport } from './routes/our-store'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BookAppointmentRouteImport } from './routes/book-appointment'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as TrackTrackingNumberRouteImport } from './routes/track.$trackingNumber'
import { Route as StoriesJournalRouteImport } from './routes/stories.journal'
import { Route as StoriesHeritageDiariesRouteImport } from './routes/stories.heritage-diaries'
import { Route as StoriesBrideStoriesRouteImport } from './routes/stories.bride-stories'
import { Route as StoriesArtisanPortraitsRouteImport } from './routes/stories.artisan-portraits'
import { Route as ShopCategoryRouteImport } from './routes/shop.$category'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as OrderStatusOrderNumberRouteImport } from './routes/order-status.$orderNumber'
import { Route as CraftZardoziRouteImport } from './routes/craft.zardozi'
import { Route as CraftHandloomWeavesRouteImport } from './routes/craft.handloom-weaves'
import { Route as CraftChikankariRouteImport } from './routes/craft.chikankari'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as CampaignsHeirloomEditRouteImport } from './routes/campaigns.heirloom-edit'
import { Route as CampaignsFestiveLookbookRouteImport } from './routes/campaigns.festive-lookbook'
import { Route as CampaignsBridal2025RouteImport } from './routes/campaigns.bridal-2025'
import { Route as CampaignsArtisanPortraitsRouteImport } from './routes/campaigns.artisan-portraits'
import { Route as AboutOutStoryRouteImport } from './routes/about.out-story'
import { Route as AboutLegacyRouteImport } from './routes/about.legacy'
import { Route as AboutFoundersVisionRouteImport } from './routes/about.founders-vision'
import { Route as AboutAtelierRouteImport } from './routes/about.atelier'
import { Route as AboutArtOfEmbroideryRouteImport } from './routes/about.art-of-embroidery'

const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingDeliveryRoute = ShippingDeliveryRouteImport.update({
  id: '/shipping-delivery',
  path: '/shipping-delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsCancellationsRoute = ReturnsCancellationsRouteImport.update({
  id: '/returns-cancellations',
  path: '/returns-cancellations',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PhilosophyRoute = PhilosophyRouteImport.update({
  id: '/philosophy',
  path: '/philosophy',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoreRoute = OurStoreRouteImport.update({
  id: '/our-store',
  path: '/our-store',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BookAppointmentRoute = BookAppointmentRouteImport.update({
  id: '/book-appointment',
  path: '/book-appointment',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackTrackingNumberRoute = TrackTrackingNumberRouteImport.update({
  id: '/$trackingNumber',
  path: '/$trackingNumber',
  getParentRoute: () => TrackRoute,
} as any)
const StoriesJournalRoute = StoriesJournalRouteImport.update({
  id: '/stories/journal',
  path: '/stories/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesHeritageDiariesRoute = StoriesHeritageDiariesRouteImport.update({
  id: '/stories/heritage-diaries',
  path: '/stories/heritage-diaries',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesBrideStoriesRoute = StoriesBrideStoriesRouteImport.update({
  id: '/stories/bride-stories',
  path: '/stories/bride-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesArtisanPortraitsRoute = StoriesArtisanPortraitsRouteImport.update({
  id: '/stories/artisan-portraits',
  path: '/stories/artisan-portraits',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCategoryRoute = ShopCategoryRouteImport.update({
  id: '/shop/$category',
  path: '/shop/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderStatusOrderNumberRoute = OrderStatusOrderNumberRouteImport.update({
  id: '/order-status/$orderNumber',
  path: '/order-status/$orderNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const CraftZardoziRoute = CraftZardoziRouteImport.update({
  id: '/craft/zardozi',
  path: '/craft/zardozi',
  getParentRoute: () => rootRouteImport,
} as any)
const CraftHandloomWeavesRoute = CraftHandloomWeavesRouteImport.update({
  id: '/craft/handloom-weaves',
  path: '/craft/handloom-weaves',
  getParentRoute: () => rootRouteImport,
} as any)
const CraftChikankariRoute = CraftChikankariRouteImport.update({
  id: '/craft/chikankari',
  path: '/craft/chikankari',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsHeirloomEditRoute = CampaignsHeirloomEditRouteImport.update({
  id: '/campaigns/heirloom-edit',
  path: '/campaigns/heirloom-edit',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsFestiveLookbookRoute =
  CampaignsFestiveLookbookRouteImport.update({
    id: '/campaigns/festive-lookbook',
    path: '/campaigns/festive-lookbook',
    getParentRoute: () => rootRouteImport,
  } as any)
const CampaignsBridal2025Route = CampaignsBridal2025RouteImport.update({
  id: '/campaigns/bridal-2025',
  path: '/campaigns/bridal-2025',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsArtisanPortraitsRoute =
  CampaignsArtisanPortraitsRouteImport.update({
    id: '/campaigns/artisan-portraits',
    path: '/campaigns/artisan-portraits',
    getParentRoute: () => rootRouteImport,
  } as any)
const AboutOutStoryRoute = AboutOutStoryRouteImport.update({
  id: '/out-story',
  path: '/out-story',
  getParentRoute: () => AboutRoute,
} as any)
const AboutLegacyRoute = AboutLegacyRouteImport.update({
  id: '/legacy',
  path: '/legacy',
  getParentRoute: () => AboutRoute,
} as any)
const AboutFoundersVisionRoute = AboutFoundersVisionRouteImport.update({
  id: '/founders-vision',
  path: '/founders-vision',
  getParentRoute: () => AboutRoute,
} as any)
const AboutAtelierRoute = AboutAtelierRouteImport.update({
  id: '/atelier',
  path: '/atelier',
  getParentRoute: () => AboutRoute,
} as any)
const AboutArtOfEmbroideryRoute = AboutArtOfEmbroideryRouteImport.update({
  id: '/art-of-embroidery',
  path: '/art-of-embroidery',
  getParentRoute: () => AboutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/accessibility': typeof AccessibilityRoute
  '/account': typeof AccountRoute
  '/book-appointment': typeof BookAppointmentRoute
  '/checkout': typeof CheckoutRoute
  '/contact-us': typeof ContactUsRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/our-store': typeof OurStoreRoute
  '/philosophy': typeof PhilosophyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/returns-cancellations': typeof ReturnsCancellationsRoute
  '/shipping-delivery': typeof ShippingDeliveryRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/track': typeof TrackRouteWithChildren
  '/about/art-of-embroidery': typeof AboutArtOfEmbroideryRoute
  '/about/atelier': typeof AboutAtelierRoute
  '/about/founders-vision': typeof AboutFoundersVisionRoute
  '/about/legacy': typeof AboutLegacyRoute
  '/about/out-story': typeof AboutOutStoryRoute
  '/campaigns/artisan-portraits': typeof CampaignsArtisanPortraitsRoute
  '/campaigns/bridal-2025': typeof CampaignsBridal2025Route
  '/campaigns/festive-lookbook': typeof CampaignsFestiveLookbookRoute
  '/campaigns/heirloom-edit': typeof CampaignsHeirloomEditRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/craft/chikankari': typeof CraftChikankariRoute
  '/craft/handloom-weaves': typeof CraftHandloomWeavesRoute
  '/craft/zardozi': typeof CraftZardoziRoute
  '/order-status/$orderNumber': typeof OrderStatusOrderNumberRoute
  '/product/$slug': typeof ProductSlugRoute
  '/shop/$category': typeof ShopCategoryRoute
  '/stories/artisan-portraits': typeof StoriesArtisanPortraitsRoute
  '/stories/bride-stories': typeof StoriesBrideStoriesRoute
  '/stories/heritage-diaries': typeof StoriesHeritageDiariesRoute
  '/stories/journal': typeof StoriesJournalRoute
  '/track/$trackingNumber': typeof TrackTrackingNumberRoute
  '/collections/': typeof CollectionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/accessibility': typeof AccessibilityRoute
  '/account': typeof AccountRoute
  '/book-appointment': typeof BookAppointmentRoute
  '/checkout': typeof CheckoutRoute
  '/contact-us': typeof ContactUsRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/our-store': typeof OurStoreRoute
  '/philosophy': typeof PhilosophyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/returns-cancellations': typeof ReturnsCancellationsRoute
  '/shipping-delivery': typeof ShippingDeliveryRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/track': typeof TrackRouteWithChildren
  '/about/art-of-embroidery': typeof AboutArtOfEmbroideryRoute
  '/about/atelier': typeof AboutAtelierRoute
  '/about/founders-vision': typeof AboutFoundersVisionRoute
  '/about/legacy': typeof AboutLegacyRoute
  '/about/out-story': typeof AboutOutStoryRoute
  '/campaigns/artisan-portraits': typeof CampaignsArtisanPortraitsRoute
  '/campaigns/bridal-2025': typeof CampaignsBridal2025Route
  '/campaigns/festive-lookbook': typeof CampaignsFestiveLookbookRoute
  '/campaigns/heirloom-edit': typeof CampaignsHeirloomEditRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/craft/chikankari': typeof CraftChikankariRoute
  '/craft/handloom-weaves': typeof CraftHandloomWeavesRoute
  '/craft/zardozi': typeof CraftZardoziRoute
  '/order-status/$orderNumber': typeof OrderStatusOrderNumberRoute
  '/product/$slug': typeof ProductSlugRoute
  '/shop/$category': typeof ShopCategoryRoute
  '/stories/artisan-portraits': typeof StoriesArtisanPortraitsRoute
  '/stories/bride-stories': typeof StoriesBrideStoriesRoute
  '/stories/heritage-diaries': typeof StoriesHeritageDiariesRoute
  '/stories/journal': typeof StoriesJournalRoute
  '/track/$trackingNumber': typeof TrackTrackingNumberRoute
  '/collections': typeof CollectionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/accessibility': typeof AccessibilityRoute
  '/account': typeof AccountRoute
  '/book-appointment': typeof BookAppointmentRoute
  '/checkout': typeof CheckoutRoute
  '/contact-us': typeof ContactUsRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/our-store': typeof OurStoreRoute
  '/philosophy': typeof PhilosophyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/returns-cancellations': typeof ReturnsCancellationsRoute
  '/shipping-delivery': typeof ShippingDeliveryRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/track': typeof TrackRouteWithChildren
  '/about/art-of-embroidery': typeof AboutArtOfEmbroideryRoute
  '/about/atelier': typeof AboutAtelierRoute
  '/about/founders-vision': typeof AboutFoundersVisionRoute
  '/about/legacy': typeof AboutLegacyRoute
  '/about/out-story': typeof AboutOutStoryRoute
  '/campaigns/artisan-portraits': typeof CampaignsArtisanPortraitsRoute
  '/campaigns/bridal-2025': typeof CampaignsBridal2025Route
  '/campaigns/festive-lookbook': typeof CampaignsFestiveLookbookRoute
  '/campaigns/heirloom-edit': typeof CampaignsHeirloomEditRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/craft/chikankari': typeof CraftChikankariRoute
  '/craft/handloom-weaves': typeof CraftHandloomWeavesRoute
  '/craft/zardozi': typeof CraftZardoziRoute
  '/order-status/$orderNumber': typeof OrderStatusOrderNumberRoute
  '/product/$slug': typeof ProductSlugRoute
  '/shop/$category': typeof ShopCategoryRoute
  '/stories/artisan-portraits': typeof StoriesArtisanPortraitsRoute
  '/stories/bride-stories': typeof StoriesBrideStoriesRoute
  '/stories/heritage-diaries': typeof StoriesHeritageDiariesRoute
  '/stories/journal': typeof StoriesJournalRoute
  '/track/$trackingNumber': typeof TrackTrackingNumberRoute
  '/collections/': typeof CollectionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/account'
    | '/book-appointment'
    | '/checkout'
    | '/contact-us'
    | '/cookie-policy'
    | '/our-store'
    | '/philosophy'
    | '/privacy-policy'
    | '/returns-cancellations'
    | '/shipping-delivery'
    | '/terms-of-service'
    | '/track'
    | '/about/art-of-embroidery'
    | '/about/atelier'
    | '/about/founders-vision'
    | '/about/legacy'
    | '/about/out-story'
    | '/campaigns/artisan-portraits'
    | '/campaigns/bridal-2025'
    | '/campaigns/festive-lookbook'
    | '/campaigns/heirloom-edit'
    | '/collections/$slug'
    | '/craft/chikankari'
    | '/craft/handloom-weaves'
    | '/craft/zardozi'
    | '/order-status/$orderNumber'
    | '/product/$slug'
    | '/shop/$category'
    | '/stories/artisan-portraits'
    | '/stories/bride-stories'
    | '/stories/heritage-diaries'
    | '/stories/journal'
    | '/track/$trackingNumber'
    | '/collections/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/account'
    | '/book-appointment'
    | '/checkout'
    | '/contact-us'
    | '/cookie-policy'
    | '/our-store'
    | '/philosophy'
    | '/privacy-policy'
    | '/returns-cancellations'
    | '/shipping-delivery'
    | '/terms-of-service'
    | '/track'
    | '/about/art-of-embroidery'
    | '/about/atelier'
    | '/about/founders-vision'
    | '/about/legacy'
    | '/about/out-story'
    | '/campaigns/artisan-portraits'
    | '/campaigns/bridal-2025'
    | '/campaigns/festive-lookbook'
    | '/campaigns/heirloom-edit'
    | '/collections/$slug'
    | '/craft/chikankari'
    | '/craft/handloom-weaves'
    | '/craft/zardozi'
    | '/order-status/$orderNumber'
    | '/product/$slug'
    | '/shop/$category'
    | '/stories/artisan-portraits'
    | '/stories/bride-stories'
    | '/stories/heritage-diaries'
    | '/stories/journal'
    | '/track/$trackingNumber'
    | '/collections'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessibility'
    | '/account'
    | '/book-appointment'
    | '/checkout'
    | '/contact-us'
    | '/cookie-policy'
    | '/our-store'
    | '/philosophy'
    | '/privacy-policy'
    | '/returns-cancellations'
    | '/shipping-delivery'
    | '/terms-of-service'
    | '/track'
    | '/about/art-of-embroidery'
    | '/about/atelier'
    | '/about/founders-vision'
    | '/about/legacy'
    | '/about/out-story'
    | '/campaigns/artisan-portraits'
    | '/campaigns/bridal-2025'
    | '/campaigns/festive-lookbook'
    | '/campaigns/heirloom-edit'
    | '/collections/$slug'
    | '/craft/chikankari'
    | '/craft/handloom-weaves'
    | '/craft/zardozi'
    | '/order-status/$orderNumber'
    | '/product/$slug'
    | '/shop/$category'
    | '/stories/artisan-portraits'
    | '/stories/bride-stories'
    | '/stories/heritage-diaries'
    | '/stories/journal'
    | '/track/$trackingNumber'
    | '/collections/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
  AccessibilityRoute: typeof AccessibilityRoute
  AccountRoute: typeof AccountRoute
  BookAppointmentRoute: typeof BookAppointmentRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactUsRoute: typeof ContactUsRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  OurStoreRoute: typeof OurStoreRoute
  PhilosophyRoute: typeof PhilosophyRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ReturnsCancellationsRoute: typeof ReturnsCancellationsRoute
  ShippingDeliveryRoute: typeof ShippingDeliveryRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  TrackRoute: typeof TrackRouteWithChildren
  CampaignsArtisanPortraitsRoute: typeof CampaignsArtisanPortraitsRoute
  CampaignsBridal2025Route: typeof CampaignsBridal2025Route
  CampaignsFestiveLookbookRoute: typeof CampaignsFestiveLookbookRoute
  CampaignsHeirloomEditRoute: typeof CampaignsHeirloomEditRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  CraftChikankariRoute: typeof CraftChikankariRoute
  CraftHandloomWeavesRoute: typeof CraftHandloomWeavesRoute
  CraftZardoziRoute: typeof CraftZardoziRoute
  OrderStatusOrderNumberRoute: typeof OrderStatusOrderNumberRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ShopCategoryRoute: typeof ShopCategoryRoute
  StoriesArtisanPortraitsRoute: typeof StoriesArtisanPortraitsRoute
  StoriesBrideStoriesRoute: typeof StoriesBrideStoriesRoute
  StoriesHeritageDiariesRoute: typeof StoriesHeritageDiariesRoute
  StoriesJournalRoute: typeof StoriesJournalRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-delivery': {
      id: '/shipping-delivery'
      path: '/shipping-delivery'
      fullPath: '/shipping-delivery'
      preLoaderRoute: typeof ShippingDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns-cancellations': {
      id: '/returns-cancellations'
      path: '/returns-cancellations'
      fullPath: '/returns-cancellations'
      preLoaderRoute: typeof ReturnsCancellationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/philosophy': {
      id: '/philosophy'
      path: '/philosophy'
      fullPath: '/philosophy'
      preLoaderRoute: typeof PhilosophyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-store': {
      id: '/our-store'
      path: '/our-store'
      fullPath: '/our-store'
      preLoaderRoute: typeof OurStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-appointment': {
      id: '/book-appointment'
      path: '/book-appointment'
      fullPath: '/book-appointment'
      preLoaderRoute: typeof BookAppointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$trackingNumber': {
      id: '/track/$trackingNumber'
      path: '/$trackingNumber'
      fullPath: '/track/$trackingNumber'
      preLoaderRoute: typeof TrackTrackingNumberRouteImport
      parentRoute: typeof TrackRoute
    }
    '/stories/journal': {
      id: '/stories/journal'
      path: '/stories/journal'
      fullPath: '/stories/journal'
      preLoaderRoute: typeof StoriesJournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/heritage-diaries': {
      id: '/stories/heritage-diaries'
      path: '/stories/heritage-diaries'
      fullPath: '/stories/heritage-diaries'
      preLoaderRoute: typeof StoriesHeritageDiariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/bride-stories': {
      id: '/stories/bride-stories'
      path: '/stories/bride-stories'
      fullPath: '/stories/bride-stories'
      preLoaderRoute: typeof StoriesBrideStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/artisan-portraits': {
      id: '/stories/artisan-portraits'
      path: '/stories/artisan-portraits'
      fullPath: '/stories/artisan-portraits'
      preLoaderRoute: typeof StoriesArtisanPortraitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$category': {
      id: '/shop/$category'
      path: '/shop/$category'
      fullPath: '/shop/$category'
      preLoaderRoute: typeof ShopCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-status/$orderNumber': {
      id: '/order-status/$orderNumber'
      path: '/order-status/$orderNumber'
      fullPath: '/order-status/$orderNumber'
      preLoaderRoute: typeof OrderStatusOrderNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/craft/zardozi': {
      id: '/craft/zardozi'
      path: '/craft/zardozi'
      fullPath: '/craft/zardozi'
      preLoaderRoute: typeof CraftZardoziRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/craft/handloom-weaves': {
      id: '/craft/handloom-weaves'
      path: '/craft/handloom-weaves'
      fullPath: '/craft/handloom-weaves'
      preLoaderRoute: typeof CraftHandloomWeavesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/craft/chikankari': {
      id: '/craft/chikankari'
      path: '/craft/chikankari'
      fullPath: '/craft/chikankari'
      preLoaderRoute: typeof CraftChikankariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/heirloom-edit': {
      id: '/campaigns/heirloom-edit'
      path: '/campaigns/heirloom-edit'
      fullPath: '/campaigns/heirloom-edit'
      preLoaderRoute: typeof CampaignsHeirloomEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/festive-lookbook': {
      id: '/campaigns/festive-lookbook'
      path: '/campaigns/festive-lookbook'
      fullPath: '/campaigns/festive-lookbook'
      preLoaderRoute: typeof CampaignsFestiveLookbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/bridal-2025': {
      id: '/campaigns/bridal-2025'
      path: '/campaigns/bridal-2025'
      fullPath: '/campaigns/bridal-2025'
      preLoaderRoute: typeof CampaignsBridal2025RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/artisan-portraits': {
      id: '/campaigns/artisan-portraits'
      path: '/campaigns/artisan-portraits'
      fullPath: '/campaigns/artisan-portraits'
      preLoaderRoute: typeof CampaignsArtisanPortraitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/out-story': {
      id: '/about/out-story'
      path: '/out-story'
      fullPath: '/about/out-story'
      preLoaderRoute: typeof AboutOutStoryRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/legacy': {
      id: '/about/legacy'
      path: '/legacy'
      fullPath: '/about/legacy'
      preLoaderRoute: typeof AboutLegacyRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/founders-vision': {
      id: '/about/founders-vision'
      path: '/founders-vision'
      fullPath: '/about/founders-vision'
      preLoaderRoute: typeof AboutFoundersVisionRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/atelier': {
      id: '/about/atelier'
      path: '/atelier'
      fullPath: '/about/atelier'
      preLoaderRoute: typeof AboutAtelierRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/art-of-embroidery': {
      id: '/about/art-of-embroidery'
      path: '/art-of-embroidery'
      fullPath: '/about/art-of-embroidery'
      preLoaderRoute: typeof AboutArtOfEmbroideryRouteImport
      parentRoute: typeof AboutRoute
    }
  }
}

interface AboutRouteChildren {
  AboutArtOfEmbroideryRoute: typeof AboutArtOfEmbroideryRoute
  AboutAtelierRoute: typeof AboutAtelierRoute
  AboutFoundersVisionRoute: typeof AboutFoundersVisionRoute
  AboutLegacyRoute: typeof AboutLegacyRoute
  AboutOutStoryRoute: typeof AboutOutStoryRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutArtOfEmbroideryRoute: AboutArtOfEmbroideryRoute,
  AboutAtelierRoute: AboutAtelierRoute,
  AboutFoundersVisionRoute: AboutFoundersVisionRoute,
  AboutLegacyRoute: AboutLegacyRoute,
  AboutOutStoryRoute: AboutOutStoryRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

interface TrackRouteChildren {
  TrackTrackingNumberRoute: typeof TrackTrackingNumberRoute
}

const TrackRouteChildren: TrackRouteChildren = {
  TrackTrackingNumberRoute: TrackTrackingNumberRoute,
}

const TrackRouteWithChildren = TrackRoute._addFileChildren(TrackRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
  AccessibilityRoute: AccessibilityRoute,
  AccountRoute: AccountRoute,
  BookAppointmentRoute: BookAppointmentRoute,
  CheckoutRoute: CheckoutRoute,
  ContactUsRoute: ContactUsRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  OurStoreRoute: OurStoreRoute,
  PhilosophyRoute: PhilosophyRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ReturnsCancellationsRoute: ReturnsCancellationsRoute,
  ShippingDeliveryRoute: ShippingDeliveryRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  TrackRoute: TrackRouteWithChildren,
  CampaignsArtisanPortraitsRoute: CampaignsArtisanPortraitsRoute,
  CampaignsBridal2025Route: CampaignsBridal2025Route,
  CampaignsFestiveLookbookRoute: CampaignsFestiveLookbookRoute,
  CampaignsHeirloomEditRoute: CampaignsHeirloomEditRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  CraftChikankariRoute: CraftChikankariRoute,
  CraftHandloomWeavesRoute: CraftHandloomWeavesRoute,
  CraftZardoziRoute: CraftZardoziRoute,
  OrderStatusOrderNumberRoute: OrderStatusOrderNumberRoute,
  ProductSlugRoute: ProductSlugRoute,
  ShopCategoryRoute: ShopCategoryRoute,
  StoriesArtisanPortraitsRoute: StoriesArtisanPortraitsRoute,
  StoriesBrideStoriesRoute: StoriesBrideStoriesRoute,
  StoriesHeritageDiariesRoute: StoriesHeritageDiariesRoute,
  StoriesJournalRoute: StoriesJournalRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
